### PR TITLE
RT-4764 fixed the job entity

### PR DESCRIPTION
**Pull request by wharrisgit**

### CODE REVIEW

**Comment by onatskyy** [comment]
This wrong changes. We can`t use in bundle logic from another bundle.

**Comment by onatskyy** [comment]
If u want do it - u should override this logic in core project.

**Comment by wharrisgit** [comment]
We use RjDataBundle:Job in RunCommand.  Changing RunCommand is outside the scope of this issue.

**Comment by onatskyy** [comment]
If you think this is correct - please give examples where such solutions are used

**Comment by wharrisgit** [comment]
I just did.  RunCommand.

**Comment by onatskyy** [comment]
I mean another bundles.

**Pull request merged**
